### ISSUE TITLE
segfault when accessing pPopulation variable

### ISSUE THREAD

**Issue by wwilly** [EASEA/easea#17]
Hi,
I try to use pPopulation variable, and I get segfault:
...
\At the end of each generation function:
  //cout << "At the end of each generation function called" << endl;
  for (int i = 0; i < 30; ++i)
  {
    printf ("%d -> %f\n", i, pPopulation[i]->fitness);
  }
\end
....

Upper bound is manual constant, https://github.com/EASEA/easea/issues/16 show the reason.

This is the output:
~/local/opt/easea/examples/sphere
$ make easeaclean && easea sphere.ez && make && ./sphere
rm -f sphere *.o *.cpp *.hpp sphere.png sphere.dat sphere.prm sphere.mak Makefile sphere.vcproj sphere.csv sphere.r sphere.plot sphere.pop
Easea v1.0.3 compiler 

CONGRATULATIONS !!!
Target file(s) generation succeeded without warnings.
You can now type "make" to compile your project.
c++ -O2 -g -Wall -fmessage-length=0 -I/Users/willy/local/opt/easea//libeasea/include -I/Users/willy/local/opt/easea/boost   -c -o sphere.o sphere.cpp
c++ -O2 -g -Wall -fmessage-length=0 -I/Users/willy/local/opt/easea//libeasea/include -I/Users/willy/local/opt/easea/boost   -c -o sphereIndividual.o sphereIndividual.cpp
c++ -o sphere sphere.o sphereIndividual.o   -g /Users/willy/local/opt/easea//libeasea//libeasea.a /Users/willy/local/opt/easea/boost/program_options.a -lpthread 
Population initialisation (Generation 0)... 
GEN TIME        EVAL        BEST      AVG       STDDEV    WORST

0   0.0     30      5.15e+02  4.25e+02  5.06e+01  3.14e+02
1   0.0     60      5.15e+02  3.94e+02  6.25e+01  2.94e+02
0 -> -158456325028528675187087900672.000000
1 -> 377.702789
2 -> 435.109009
3 -> -158456325028528675187087900672.000000
4 -> 483.657410
5 -> 469.806946
6 -> 441.076874
7 -> -158456325028528675187087900672.000000
8 -> 415.802917
9 -> 486.462280
10 -> 362.311493
11 -> 395.318634
12 -> 336.013367
13 -> 442.540161
14 -> 436.372589
15 -> 370.143066
16 -> -158456325028528675187087900672.000000
17 -> 469.712097
18 -> 468.022034
19 -> 458.468781
20 -> -158494897317960754449193369600.000000
21 -> 397.359924
22 -> -158494897317960754449193369600.000000
23 -> 314.398346
24 -> 358.745361
25 -> 448.910187
26 -> 0.000000
27 -> 358.774384
28 -> 434.593201
Segmentation fault: 11

The documentation http://easea.unistra.fr/easea/index.php/EASEA_defined_variables#Population say that the variable can't be accessed anywhere, but at http://easea.unistra.fr/easea/index.php/EASEA_defined_sections#At_the_end_of_each_generation_function, we can read "The population can be accessed.", I assume that population is pPopulation.

Best Regards,
Willy.

**Comment by wwilly** [comment]
I change the code to:
...
\At the end of each generation function:
  //cout << "At the end of each generation function called" << endl;
  for (int i = 0; i < 30; ++i)
  {
    printf ("@pPopulation[%d] -> %p\n", i, pPopulation[i]);
    printf ("fitness %f\n", pPopulation[i]->fitness);
  }
\end
...

the output:
~/local/opt/easea/examples/sphere
$ make easeaclean && easea sphere.ez && make && ./sphere
rm -f sphere *.o *.cpp *.hpp sphere.png sphere.dat sphere.prm sphere.mak Makefile sphere.vcproj sphere.csv sphere.r sphere.plot sphere.pop
Easea v1.0.3 compiler 

CONGRATULATIONS !!!
Target file(s) generation succeeded without warnings.
You can now type "make" to compile your project.
c++ -O2 -g -Wall -fmessage-length=0 -I/Users/willy/local/opt/easea//libeasea/include -I/Users/willy/local/opt/easea/boost   -c -o sphere.o sphere.cpp
c++ -O2 -g -Wall -fmessage-length=0 -I/Users/willy/local/opt/easea//libeasea/include -I/Users/willy/local/opt/easea/boost   -c -o sphereIndividual.o sphereIndividual.cpp
c++ -o sphere sphere.o sphereIndividual.o   -g /Users/willy/local/opt/easea//libeasea//libeasea.a /Users/willy/local/opt/easea/boost/program_options.a -lpthread 
Population initialisation (Generation 0)... 
GEN	TIME		EVAL		BEST      AVG       STDDEV    WORST

0	0.0		30		5.37e+02  4.25e+02  5.01e+01  3.42e+02
1	0.0		60		5.37e+02  4.02e+02  6.46e+01  2.94e+02
@((IndividualImpl*)pPopulation[0]) -> 0x7f9fe8c06b80
fitness -8589934592.000000
@((IndividualImpl*)pPopulation[1]) -> 0x7f9fe8c07370
fitness -8589934592.000000
@((IndividualImpl*)pPopulation[2]) -> 0x7f9fe8c04c70
fitness 520.222168
@((IndividualImpl*)pPopulation[3]) -> 0x7f9fe8c04e10
fitness 370.623260
@((IndividualImpl*)pPopulation[4]) -> 0x7f9fe8c05040
fitness 429.115204
@((IndividualImpl*)pPopulation[5]) -> 0x7f9fe8c051e0
fitness 425.110352
@((IndividualImpl*)pPopulation[6]) -> 0x7f9fe8c08060
fitness 471.347900
@((IndividualImpl*)pPopulation[7]) -> 0x7f9fe8c08200
fitness 451.404694
@((IndividualImpl*)pPopulation[8]) -> 0x7f9fe8c083a0
fitness 524.717896
@((IndividualImpl*)pPopulation[9]) -> 0x7f9fe8c08540
fitness -8589934592.000000
@((IndividualImpl*)pPopulation[10]) -> 0x7f9fe8c086e0
fitness 429.643768
@((IndividualImpl*)pPopulation[11]) -> 0x7f9fe8c08880
fitness 396.210175
@((IndividualImpl*)pPopulation[12]) -> 0x7f9fe8c099d0
fitness 424.466248
@((IndividualImpl*)pPopulation[13]) -> 0x7f9fe8c09b70
fitness -8589934592.000000
@((IndividualImpl*)pPopulation[14]) -> 0x7f9fe8c09d10
fitness 393.949921
@((IndividualImpl*)pPopulation[15]) -> 0x7f9fe8c0b0e0
fitness 342.000244
@((IndividualImpl*)pPopulation[16]) -> 0x7f9fe8c0b280
fitness 466.815430
@((IndividualImpl*)pPopulation[17]) -> 0x7f9fe8c0b420
fitness 425.545532
@((IndividualImpl*)pPopulation[18]) -> 0x7f9fe8c0b5c0
fitness 410.057343
@((IndividualImpl*)pPopulation[19]) -> 0x7f9fe8c0b760
fitness 8592024576.000000
@((IndividualImpl*)pPopulation[20]) -> 0x7f9fe8c0b900
fitness 370.538727
@((IndividualImpl*)pPopulation[21]) -> 0x7f9fe8c0c7a0
fitness 461.119720
@((IndividualImpl*)pPopulation[22]) -> 0x7f9fe8c0bc40
fitness 352.657501
@((IndividualImpl*)pPopulation[23]) -> 0x7f9fe8c0bde0
fitness 2.000487
@((IndividualImpl*)pPopulation[24]) -> 0x7f9fe8c0bf80
fitness 414.283600
@((IndividualImpl*)pPopulation[25]) -> 0x7f9fe8c0c120
fitness 469.248047
@((IndividualImpl*)pPopulation[26]) -> 0x7f9fe8c0c2c0
fitness 440.688599
@((IndividualImpl*)pPopulation[27]) -> 0x7f9fe8c0c460
fitness 419.468231
@((IndividualImpl*)pPopulation[28]) -> 0x7f9fe8c0c600
fitness 366.344818
@((IndividualImpl*)pPopulation[29]) -> 0x0
Segmentation fault: 11



How did you access the fitness for printing?

**Comment by pallamidessi** [comment]
Hi,

You actually did use the correct way to print the fitness ( "printf ("fitness %f\n", pPopulation[i]->fitness);" ) but this you're close to the initialisation, the outliners you're seeing are possibles.

The segfault might be due to the fact that by default, an elite population is defined with one element. Since your population have 30 individuals, the 30th one do not possibly exist in this structure.

Of course, it's an educated guess, I will dig into it more deeply this wek-end.

Regards,

**Comment by zeFresk** [comment]
Fixed in a PR.

The pointer pPopulation was not updated after the first generation and lead to this bug. (After 1 generation pPopulation pointed to freed memory)
