### ISSUE TITLE
include macro enhancement

### ISSUE THREAD

**Issue by rahya** [EASEA/easea#18]
Yup,

you can improve the readability of your code by avoiding to write all your code in the same file
Example : 
float result = 0.;
# include "evaluator.ez"

return result;

2 problems:
- #include is not handle by easea and then the Genome definition isn't change to the definition that lead to compilation error. 
- As discussed, the generated expression in evaluator area (return fitness = result) create unexpected behaviour if the return instruction is in the included file. (fitness is uninitialized)

**Comment by pallamidessi** [comment]
Ok, a few pointers for achieving that with the current version of easea.

In your "evaluator.ez" you must provide a main wrapper taking a IndividualImpl* argument.

All your calls to EASEA's convenience function for random number generation must be prefixed by  globalRandomGenerator->random(...) .

For your evaluator.ez, the main wrapper must be define as WRAPPER_NAME(IndividualImpl&) and called from the evaluator section as WRAPPER_NAME(Genome)

For your crossover.ez, the main wrapper must be define as WRAPPER_NAME(IndividualImpl&, IndividualImpl&, IndividualImpl&) and called from the crossover section as WRAPPER_NAME(parent1, parent2, child)

You can see a example of this workaround in the examples directory  packaged with EASEA, in peculiar in the regression_okto_real examples.
