### ISSUE TITLE
Bug with parameter ipFile when using gp flag

### ISSUE THREAD

**Issue by NukesRadars** [EASEA/easea#21]
Hi,
I get a bug when trying to run a GP program with island model. I'm using the branch **easea_v2.0**
If I take the regression example and run mutliple islands with a correctly formatted ipFile:

`./regression --nbGen 200 --remoteIslandModel 1 --ipFile ip.txt --serverPort 2000`
`./regression --nbGen 200 --remoteIslandModel 1 --ipFile ip.txt --serverPort 2001`

I get this message:
```
EASEA LOG [INFO]: nbGen is declared in user command line as 10
 ip file : nbGen contains 0 client ip(s)
***WARNING***
No islands to communicate with.
```

**Comment by zeFresk** [comment]
This should have been fixed in #51 with the CLI refactoring. Also, the island model was rewritten from scratch in EASEA 3.0
