### ISSUE TITLE
Documentation is not consistently reachable

### ISSUE THREAD

**Issue by DrCrowller** [EASEA/easea#31]
When trying to open the documentation in private browsing, the documentation redirects the URL toward iCube's intranet.

Opening this URL in private browsing mode with Firefox :
http://easea.unistra.fr/index.php/Starting_with_EASEA

Leads to this URL :
https://intranet.icube.unistra.fr/index.php/Starting_with_EASEA

Which pops a 404 error.
This appears to be an HTTP redirect.

**Comment by zeFresk** [comment]
This seems to have been fixed. I will close.
